Explicitly install additional libraries
sourcebots/pi-image pull request #7
Opened 2017-12-03 21:33 UTC by RealOrangeOne

Sometimes, using additional libraries in robot code helps a lot, especially in cementing real-world use cases for Python. Now we can explicitly install libraries into the environment to be used, outside of the ones our applications depend on.

Docs page created in https://github.com/sourcebots/docs/pull/42

(This PR doesn't add any additional ones, just adds `scipy` and `numpy` explicitly)

2017-12-03 21:47 UTC, PeterJCLaw approved these changes
Please add missing trailing newline before merge, otherwise seems fine.

2017-12-03 21:47 UTC, PeterJCLaw commented on pi-main.sh
> +pip install -r /additional-libraries.txt
Please add a trailing newline character here.

2017-12-04 20:37 UTC, prophile requested changes
I think we should install these from the Debian repositories rather than through pip.

In the Debian case this will pull in the optimised native dependencies (LAPACK and BLAS for instance) for the target, whereas with `pip` we will be resorting to pessimistic wheels if they're available and a failing build from source if they're not.

2017-12-07 23:43 UTC, PeterJCLaw commented
@RealOrangeOne Can you clarify what you mean by this not adding any extra libraries?

(separately, I think that https://github.com/sourcebots/sb-vision should have an explicit dependency on `numpy`, which I'll look at if I get time)

2017-12-08 00:12 UTC, PeterJCLaw commented
Ah, just spotted that https://github.com/sourcebots/sb-vision does indeed have a dependency on `numpy`. I'm not sure why it has the dependency on `scipy` though.

2017-12-08 08:41 UTC, RealOrangeOne commented
@PeterJCLaw I mean that this just adds the mechanism for adding additional libraries. It only installs 2 libraries, both of which would be installed by libraries that depend on them (in this case `sb-vision`)

2017-12-09 19:47 UTC, merged